spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hr
    username: sa
    password:
    driver-class-nme: org.ht.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#      show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug